# Generated by Django 4.2.9 on 2024-02-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="actions",
        ),
    ]
