# Generated by Django 4.2.9 on 2024-02-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0002_remove_product_actions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="count",
        ),
    ]
